// bookconnect-ui/src/components/NavBar/NavBar.jsx
import React, { useState } from "react";
import "./NavBar.css";
import { Link, useNavigate } from "react-router-dom";
import { RxHamburgerMenu } from "react-icons/rx";
import { useAuth } from "../../context/AuthContent";

export default function NavBar(props) {
  const [menuOpen, setMenuOpen] = useState(false);
  const navigate = useNavigate();
  const { authState, logout } = useAuth();
  const { isAuthenticated } = authState;

  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };

  const handleGetStarted = () => {
    navigate("/get-started");
    setMenuOpen(false);
  };

  const handleLogout = () => {
    setMenuOpen(false);
    logout();
    navigate('/get-started')
  };

  return (
    <>
      <nav>
        <div className="logo">BookConnect</div>
        <label htmlFor="menu-btn" className="menu-btn" onClick={toggleMenu}>
          <RxHamburgerMenu size={30} cursor="pointer" />
        </label>
        <ul className={menuOpen ? "show" : ""}>
          <li>
            <Link to="/" onClick={toggleMenu}>
              Home
            </Link>
          </li>
          <li>
            <Link to="/book-shelf" onClick={toggleMenu}>
              BookShelf
            </Link>
          </li>
          <li>
            {isAuthenticated ? (
              <button className="button" onClick={handleLogout}>
                <span>Logout</span>
              </button>
            ) : (
              <button className="button" onClick={handleGetStarted}>
                <span>Get Started</span>
              </button>
            )}
          </li>
        </ul>
      </nav>
    </>
  );
}

// bookconnect-ui/src/app/components/navbar/navbar.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { AuthContextService } from '../../shared/auth-context.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css',
})
export class NavbarComponent {
  menuOpen = false;
  isAuthenticated: boolean  = false;
  constructor(
    private router: Router,
    private authContextService: AuthContextService,
    private authService: AuthService
  ) {
    this.authContextService.getAuthenticationStatus().subscribe(status => {
      this.isAuthenticated = status;
    })
  }

  toggleMenu() {
    this.menuOpen = !this.menuOpen;
  }

  handleGetStarted() {
    this.router.navigate(['/get-started']);
    this.menuOpen = false;
  }

  handleLogout() {
    this.authService.onLogout();
    this.router.navigate(['/home']);
    this.menuOpen = false;
  }
}

<nav>
    <div class="logo">
      <a routerLink="/" class="logo-link">
        <span class="material-symbols-outlined bookconnect-logo">
            library_books
        </span>
        <span class="logo-text">BookConnect</span>
      </a>
    </div>
        <label for="menu-btn" class="menu-btn" (click)="toggleMenu()">
      <span class="material-symbols-outlined">
        menu
      </span>
    </label>
    <ul [ngClass]="{ 'show': menuOpen }">
      <li>
        <a routerLink="/home" (click)="toggleMenu()">Home</a>
      </li>
      <li>
        <a routerLink="/library" (click)="toggleMenu()">LIBRARY</a>
      </li>
      <li>
        <a routerLink="/book-shelf" (click)="toggleMenu()">BookShelf</a>
      </li>
      <li>
        <a routerLink="/add-book" (click)="toggleMenu()">ADD BOOK</a>
      </li>
      <li>
        <a routerLink="/my-books" (click)="toggleMenu()">MY BOOKS</a>
      </li>
      <li>
        <button class="button" (click)="isAuthenticated ? handleLogout() : handleGetStarted()">
          <!-- <span>{{ isAuthenticated ? 'Logout' : 'Get Started' }}</span> -->
          <span *ngIf="isAuthenticated">Logout</span>
          <span *ngIf="!isAuthenticated">Get Started!</span>
        </button>
      </li>
    </ul>
  </nav>
  <!-- Temp solution -->
  <div class="navbar-spacer"></div>
